# Generated by Django 3.1.2 on 2020-10-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_terms", "0004_auto_20201018_1640"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="synonym",
            unique_together={("source", "target")},
        ),
    ]
