# Generated by Django 3.1 on 2020-09-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0004_auto_20200924_2105'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                name='UserAnnotation',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='UserAnnotation',
                    table='selia_annotator_userannotation',
                ),
            ]
        ),
    ]
