# Generated by Django 3.1 on 2020-09-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0005_delete_userannotation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AnnotationTool',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='AnnotationTool',
                    table='selia_annotator_annotationtool',
                ),
            ],
        )
    ]
