# Generated by Django 3.1 on 2020-10-12 21:13

from django.db import migrations, models
import django.db.models.deletion


def move_collection_to_collectionlicence(apps, schema_editor):
    Licence = apps.get_model("irekua_database", "Licence")
    CollectionLicence = apps.get_model("irekua_database", "CollectionLicence")

    for licence in Licence.objects.all():
        collection_licence = CollectionLicence(
            collection_tmp=licence.collection,
            licence_ptr=licence,
        )
        collection_licence.__dict__.update(licence.__dict__)
        collection_licence.save()

    assert Licence.objects.count() == CollectionLicence.objects.count()


class Migration(migrations.Migration):

    dependencies = [
        (
            "irekua_database",
            "0006_migrate_sampling_event_device_into_deployment",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionLicence",
            fields=[
                (
                    "licence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_database.licence",
                    ),
                ),
                (
                    "collection_tmp",
                    models.ForeignKey(
                        db_column="collection_id",
                        help_text="Collection to which this licence belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irekua_database.collection",
                        verbose_name="collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Licence",
                "verbose_name_plural": "Collection Licences",
                "ordering": ["-created_on"],
            },
            bases=("irekua_database.licence",),
        ),
        migrations.RunPython(
            move_collection_to_collectionlicence,
        ),
        migrations.RemoveField(
            model_name="licence",
            name="collection",
        ),
        migrations.RenameField(
            model_name="collectionlicence",
            old_name="collection_tmp",
            new_name="collection",
        ),
    ]
