# Generated by Django 3.1 on 2020-10-12 01:43

from uuid import uuid4
from django.db import migrations, models


def move_sampling_event_types_to_deployment_types(apps, schema_editor):
    SamplingEventType = apps.get_model('irekua_database', 'SamplingEventType')
    DeploymentType = apps.get_model('irekua_database', 'DeploymentType')

    for sampling_event_type in SamplingEventType.objects.all():
        for device_type in sampling_event_type.device_types.all():
            deployment = DeploymentType.objects.get(
                sampling_event_type=sampling_event_type,
                device_type=device_type
            )

            sampling_event_type.deployment_types.add(deployment)
        sampling_event_type.save()

        # Check that the number of deployment types is correct
        assert sampling_event_type.deployment_types.count() == sampling_event_type.device_types.count()


def add_dummy_name(apps, schema_editor):
    DeploymentType = apps.get_model('irekua_database', 'DeploymentType')
    for deployment_type in DeploymentType.objects.all():
        deployment_type.name = uuid4()
        deployment_type.save()


def default_name():
    return f'change me now - {uuid4()}'


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0008_move_terms'),
        ('irekua_terms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplingEventTypeDeviceType',
            new_name='DeploymentType',
        ),
        migrations.RenameField(
            model_name='samplingeventtype',
            old_name='restrict_device_types',
            new_name='restrict_deployment_types',
        ),
        migrations.AlterField(
            model_name='samplingeventtype',
            name='restrict_deployment_types',
            field=models.BooleanField(db_column='restrict_deployment_types', default=False, help_text='Flag indicating whether to restrict deployment types associated with this sampling event type', verbose_name='restrict deployment types'),
        ),
        migrations.AddField(
            model_name='samplingeventtype',
            name='deployment_types',
            field=models.ManyToManyField(blank=True, help_text='Valid deployment types for this sampling event type', to='irekua_database.DeploymentType', verbose_name='deployment types'),
        ),
        migrations.AlterModelOptions(
            name='deploymenttype',
            options={'verbose_name': 'Deployment Type', 'verbose_name_plural': 'Deployment Types'},
        ),
        migrations.AddField(
            model_name='deploymenttype',
            name='description',
            field=models.TextField(blank=True, db_column='description', help_text='Description of deployment type', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='deploymenttype',
            name='icon',
            field=models.ImageField(blank=True, db_column='icon', help_text='Icon for deployment type', null=True, upload_to='images/deployment_types/', verbose_name='icon'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymenttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deploymenttype',
            name='name',
            field=models.CharField(db_column='name', help_text='Name of deployment type', max_length=128, null=True, verbose_name='name'),
        ),
        migrations.RunPython(
            code=add_dummy_name,
        ),
        migrations.AlterField(
            model_name='deploymenttype',
            name='name',
            field=models.CharField(db_column='name', help_text='Name of deployment type', max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.RunPython(
            code=move_sampling_event_types_to_deployment_types,
        ),
        migrations.RemoveField(
            model_name='samplingeventtype',
            name='device_types',
        ),
        migrations.RemoveField(
            model_name='deploymenttype',
            name='sampling_event_type',
        ),
    ]
