# Generated by Django 3.1 on 2020-10-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_database", "0008_add_item_subclasses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="deployment",
        ),
        migrations.RemoveField(
            model_name="item",
            name="item_thumbnail",
        ),
        migrations.RenameField(
            model_name="deploymentitem",
            old_name="deployment_tmp",
            new_name="deployment",
        ),
    ]
