# Generated by Django 3.1 on 2020-10-13 02:00
from functools import lru_cache
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user_institutions(apps, schema_editor):
    User = apps.get_model("irekua_database", "User")
    UserInstitution = apps.get_model("irekua_database", "UserInstitution")
    Institution = apps.get_model("irekua_database", "Institution")

    @lru_cache()
    def get_institution_by_name(name):
        return Institution.objects.filter(institution_name=name).first()

    for user in User.objects.all():
        institution = user.institution

        if not institution:
            continue

        name = institution.institution_name
        user_institution = UserInstitution(
            institution=get_institution_by_name(name),
            user=user,
            subdependency=institution.subdependency,
        )

        user_institution.save()

    assert (
        UserInstitution.objects.count()
        == User.objects.filter(institution__isnull=False).count()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_database", "0010_massive_migration_to_submodules"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_on",
                        help_text="Date of creation",
                        verbose_name="created on",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified_on",
                        help_text="Date of last modification",
                        verbose_name="modified on",
                    ),
                ),
                (
                    "subdependency",
                    models.CharField(
                        blank=True,
                        db_column="subdependency",
                        help_text="Subdependency at institution to which the user belongs",
                        max_length=256,
                        null=True,
                        verbose_name="subdependency",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        db_column="position",
                        help_text="Position held by the user in the institution",
                        max_length=128,
                        null=True,
                        verbose_name="position",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institution_id",
                        help_text="Institution to which the user belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_database.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="User that belongs to this institution",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Institution",
                "verbose_name_plural": "User Institutions",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="institutions",
            field=models.ManyToManyField(
                help_text="Institutions to which the user belongs",
                through="irekua_database.UserInstitution",
                to="irekua_database.Institution",
                verbose_name="user institutions",
            ),
        ),
        migrations.RunPython(
            add_user_institutions,
        ),
    ]
