# Generated by Django 3.1 on 2020-10-13 02:00
from functools import lru_cache
from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    Institution = apps.get_model("irekua_database", "Institution")

    @lru_cache()
    def get_institution_by_name(name):
        return Institution.objects.filter(institution_name=name).first()

    for institution in Institution.objects.all():
        representative = get_institution_by_name(institution.institution_name)

        if institution.pk == representative.pk:
            continue

        # Change users institution to representative
        for user_institution in institution.userinstitution_set.all():
            user_institution.institution = representative
            user_institution.save()

        # Change institution collections
        for collection in institution.collection_set.all():
            collection.institution = representative
            collection.save()

        institution.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_database", "0011_create_user_institutions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="institution",
        ),
        migrations.AlterUniqueTogether(
            name="institution",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="institution",
            name="subdependency",
        ),
        migrations.RunPython(
            remove_duplicates,
        ),
    ]
