# Generated by Django 3.1 on 2020-10-18 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0016_clean_user_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='users',
            field=models.ManyToManyField(help_text='Users belonging to this institution', through='irekua_database.UserInstitution', to=settings.AUTH_USER_MODEL, verbose_name="Institution's user"),
        ),
    ]
