# Generated by Django 3.1.2 on 2020-10-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0017_institution_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinstitution',
            unique_together={('institution', 'user')},
        ),
    ]
