# Generated by Django 3.1.2 on 2020-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationvote',
            options={'ordering': ['-created_on'], 'verbose_name': 'Annotation Vote', 'verbose_name_plural': 'Annotation Votes'},
        ),
        migrations.AddField(
            model_name='annotationvote',
            name='incorrect_geometry',
            field=models.BooleanField(blank=True, db_column='incorrect_geometry', default=False, help_text='Is the annotation geometry incorrect?', verbose_name='incorrect geometry'),
        ),
        migrations.AlterField(
            model_name='item',
            name='filesize',
            field=models.IntegerField(blank=True, db_column='filesize', help_text='Size of resource in bytes', null=True, verbose_name='file size'),
        ),
    ]
