# Generated by Django 3.1.2 on 2020-10-19 21:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irekua_items', '0002_auto_20201019_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationvote',
            unique_together={('annotation', 'created_by')},
        ),
    ]
