# Generated by Django 3.1.2 on 2020-10-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_items', '0010_relocate_annotation_models'),
        ('irekua_thumbnails', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ItemThumbnail',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='ItemThumbnail',
                    table='irekua_thumbnails_itemthumbnail',
                ),
            ],
        ),
    ]
