# Generated by Django 3.1.2 on 2020-12-18 03:03

from django.db import migrations, models
import django.db.models.deletion


def move_media_info_schema_into_type(apps, schema_editor):
    MimeType = apps.get_model("irekua_items", "MimeType")
    MediaInfoType = apps.get_model("irekua_items", "MediaInfoType")

    for mime_type in MimeType.objects.all():
        media_info_schema = mime_type.media_info_schema

        if media_info_schema is None:
            continue

        name = media_info_schema.name
        description = media_info_schema.description

        media_info_type, _ = MediaInfoType.objects.get_or_create(
            media_info_schema=media_info_schema,
            defaults={
                "name": name,
                "description": description,
            },
        )

        mime_type.media_info_type = media_info_type
        mime_type.save()

        assert (
            mime_type.media_info_type.media_info_schema
            == mime_type.media_info_schema
        )


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_items", "0013_mediainfoextractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mimetype",
            name="media_info_type",
            field=models.ForeignKey(
                blank=True,
                db_column="media_info_type_id",
                help_text="Media info type for files of this mime type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_info_type",
                to="irekua_items.mediainfotype",
                verbose_name="media info type",
            ),
        ),
        migrations.RunPython(
            move_media_info_schema_into_type,
        ),
        migrations.RemoveField(
            model_name="mimetype",
            name="media_info_schema",
        ),
    ]
