# Generated by Django 3.1 on 2021-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_items", "0014_auto_20201217_2103"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="MediaInfoExtractor",
                    table="irekua_upload_mediainfoextractor",
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="MediaInfoExtractor",
                ),
            ],
        )
    ]
