version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - env
    depends_on:
      - db
    command: ["sleep 5"]
    environment:
      - IREKUA_DATABASE_HOST=db
      - IREKUA_DATABASE_PORT=5432

  db:
    image: postgis/postgis
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    postgis-data:

