# Generated by Django 3.1.2 on 2020-10-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_annotations', '0003_annotation_userannotation'),
        ('selia_annotator', '0005_create_updated_annotator_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationAnnotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('annotation', models.OneToOneField(db_column='annotation_id', help_text='Annotation that was created with this  annotator.', on_delete=django.db.models.deletion.CASCADE, to='irekua_annotations.annotation', verbose_name='annotation')),
                ('annotator_version', models.ForeignKey(db_column='annotator_version_id', help_text='Annotator version used to create this annotation', on_delete=django.db.models.deletion.PROTECT, to='selia_annotator.annotatorversion', verbose_name='annotator version')),
            ],
            options={
                'verbose_name': 'Annotation Annotator',
                'verbose_name_plural': 'Annotation Annotators',
                'ordering': ['-created_on'],
            },
        ),
    ]
