# Generated by Django 3.1.2 on 2020-10-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_schemas', '0002_auto_20201018_2158'),
        ('selia_annotator', '0007_auto_20201024_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationannotator',
            name='annotator_configuration',
            field=models.JSONField(blank=True, db_column='annotator_configuration', help_text='Configuration of annotator at annotation creation', null=True, verbose_name='annotator configuration'),
        ),
        migrations.AddField(
            model_name='annotatorversion',
            name='configuration_schema',
            field=models.ForeignKey(blank=True, db_column='configuration_schema', help_text='JSON schema for annotator configuration', null=True, on_delete=django.db.models.deletion.PROTECT, to='irekua_schemas.schema', verbose_name='configuration schema'),
        ),
    ]
