# Generated by Django 3.1 on 2020-10-13 13:43

from django.db import migrations, models
import irekua_schemas.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('name', models.CharField(db_column='name', help_text='Name of schema', max_length=256, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, db_column='description', help_text='Schema description', verbose_name='description')),
                ('schema', models.JSONField(db_column='schema', help_text='JSON Schema', validators=[irekua_schemas.utils.validate_JSON_schema], verbose_name='schema')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemata',
                'ordering': ['-created_on'],
            },
        ),
    ]
