# Generated by Django 3.1.2 on 2020-11-11 21:30

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def move_site_to_point_site(apps, schema_editor):
    Site = apps.get_model("irekua_geo", "Site")
    PointSite = apps.get_model("irekua_geo", "PointSite")

    for site in Site.objects.all():
        point_site = PointSite(
            site_ptr=site,
            geometry=site.geo_ref,
            latitude_tmp=site.latitude,
            longitude_tmp=site.longitude,
            altitude_tmp=site.altitude,
        )

        point_site.__dict__.update(site.__dict__)
        point_site.save()

        assert site.geo_ref == point_site.geo_ref

    assert PointSite.objects.count() == Site.objects.count()


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_geo", "0004_auto_20201021_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineStringSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        db_column="geometry",
                        help_text="LineString geometry of site",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
            ],
            options={
                "verbose_name": "LineString Site",
                "verbose_name_plural": "LineString Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.CreateModel(
            name="MultiLineStringSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        db_column="geometry",
                        help_text="MultiLine geometry of site",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
            ],
            options={
                "verbose_name": "MultiLineString Site",
                "verbose_name_plural": "MultiLineString Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.CreateModel(
            name="MultiPointSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        db_column="geometry",
                        help_text="MultiPoint geometry of site",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
            ],
            options={
                "verbose_name": "MultiPoint Site",
                "verbose_name_plural": "MultiPoint Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.CreateModel(
            name="MultiPolygonSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        db_column="geometry",
                        help_text="MultiPolygon geometry of site",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
            ],
            options={
                "verbose_name": "MultiPolygon Site",
                "verbose_name_plural": "MultiPolygon Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.CreateModel(
            name="PolygonSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        db_column="geometry",
                        help_text="Polygon geometry of site",
                        srid=4326,
                        verbose_name="geometry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Polygon Site",
                "verbose_name_plural": "Polygon Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.CreateModel(
            name="PointSite",
            fields=[
                (
                    "site_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_geo.site",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        db_column="geo_ref",
                        help_text="Georeference of site as Geometry",
                        srid=4326,
                        verbose_name="geo ref",
                    ),
                ),
                (
                    "latitude_tmp",
                    models.FloatField(
                        blank=True,
                        db_column="latitude",
                        help_text="Latitude of site (in decimal degrees)",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude_tmp",
                    models.FloatField(
                        blank=True,
                        db_column="longitude",
                        help_text="Longitude of site (in decimal degrees)",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "altitude_tmp",
                    models.FloatField(
                        blank=True,
                        db_column="altitude",
                        help_text="Altitude of site (in meters)",
                        null=True,
                        verbose_name="altitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point Site",
                "verbose_name_plural": "Point Sites",
                "ordering": ["-created_on"],
            },
            bases=("irekua_geo.site",),
        ),
        migrations.RunPython(
            move_site_to_point_site,
        ),
        migrations.RemoveField(
            model_name="site",
            name="altitude",
        ),
        migrations.RemoveField(
            model_name="site",
            name="geo_ref",
        ),
        migrations.RemoveField(
            model_name="site",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="site",
            name="longitude",
        ),
        migrations.RenameField(
            model_name="pointsite",
            old_name="latitude_tmp",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="pointsite",
            old_name="longitude_tmp",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="pointsite",
            old_name="altitude_tmp",
            new_name="altitude",
        ),
    ]
