# Generated by Django 3.1.2 on 2020-11-11 22:11

from django.db import migrations, models


GEOMETRIES = [
    "LineString",
    "MultiLineString",
    "MultiPoint",
    "MultiPolygon",
    "Point",
    "Polygon",
]


def add_geometry_type_to_site(apps, schema_editor):
    Site = apps.get_model("irekua_geo", "Site")

    for site in Site.objects.all():
        for geom in GEOMETRIES:
            modelname = geom.lower() + "site"

            try:
                geom_site = getattr(site, modelname)
                site.geometry_type = geom_site.geometry.geom_type
                site.save()
                break

            except:
                continue

        else:
            raise RuntimeError(f"Site {site} has no geometry")


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_geo", "0005_add_geometries"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="geometry_type",
            field=models.CharField(
                choices=[
                    ("LineString", "LineString"),
                    ("MultiLineString", "MultiLineString"),
                    ("MultiPoint", "MultiPoint"),
                    ("MultiPolygon", "MultiPolygon"),
                    ("Point", "Point"),
                    ("Polygon", "Polygon"),
                ],
                db_column="geometry_type",
                default="",
                help_text="Type of geometry of site",
                max_length=16,
                verbose_name="geometry type",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_geometry_type_to_site,
        ),
        migrations.AddField(
            model_name="sitetype",
            name="linestring_site",
            field=models.BooleanField(
                blank=True,
                db_column="linestring_site",
                default=True,
                help_text="Determines if linestring sites can be of this type",
                verbose_name="linestring site",
            ),
        ),
        migrations.AddField(
            model_name="sitetype",
            name="multilinestring_site",
            field=models.BooleanField(
                blank=True,
                db_column="multilinestring_site",
                default=True,
                help_text="Determines if multilinestring sites can be of this type",
                verbose_name="multilinestring site",
            ),
        ),
        migrations.AddField(
            model_name="sitetype",
            name="multipoint_site",
            field=models.BooleanField(
                blank=True,
                db_column="multipoint_site",
                default=True,
                help_text="Determines if multipoint sites can be of this type",
                verbose_name="multipoint site",
            ),
        ),
        migrations.AddField(
            model_name="sitetype",
            name="multipolygon_site",
            field=models.BooleanField(
                blank=True,
                db_column="multipolygon_site",
                default=True,
                help_text="Determines if multipolygon sites can be of this type",
                verbose_name="multipolygon site",
            ),
        ),
        migrations.AddField(
            model_name="sitetype",
            name="point_site",
            field=models.BooleanField(
                blank=True,
                db_column="point_site",
                default=True,
                help_text="Determines if point sites can be of this type",
                verbose_name="point site",
            ),
        ),
        migrations.AddField(
            model_name="sitetype",
            name="polygon_site",
            field=models.BooleanField(
                blank=True,
                db_column="polygon_site",
                default=True,
                help_text="Determines if polygon sites can be of this type",
                verbose_name="polygon site",
            ),
        ),
    ]
