# Generated by Django 3.1.2 on 2020-12-03 03:28

from django.conf import settings
from django.db import migrations, models


def move_localities(apps, schema_editor):
    Site = apps.get_model("irekua_geo", "Site")

    for site in Site.objects.all():
        locality = site.locality

        if locality is None:
            continue

        site.localities.add(locality)
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irekua_geo", "0008_add_subsite_type_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="localities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Localities in which the site is located",
                to="irekua_geo.Locality",
                verbose_name="locality",
            ),
        ),
        migrations.RunPython(
            move_localities,
        ),
        migrations.RemoveField(
            model_name="site",
            name="locality",
        ),
    ]
