# Generated by Django 3.1.2 on 2020-10-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_annotators", "0006_annotationannotator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationtoolcomponent",
            name="annotation_tool",
        ),
        migrations.DeleteModel(
            name="AnnotationTool",
        ),
        migrations.DeleteModel(
            name="AnnotationToolComponent",
        ),
    ]
