# Generated by Django 3.1.2 on 2020-10-19 03:00
import json

from django.db import migrations, models
import django.db.models.deletion


def move_json_schema_to_foreign_key(model_name, field):
    def python_migration(apps, schema_editor):
        Schema = apps.get_model("irekua_schemas", "Schema")
        Model = apps.get_model("irekua_types", model_name)

        schemas = {}

        def get_schema_object_from_schema(schema):
            if isinstance(schema, str):
                schema = json.loads(schema)

            title = schema.get("title", None)
            description = schema.get("description", "")

            if title is None:
                return None

            if title in schemas:
                return schemas[title]

            schema_object, _ = Schema.objects.get_or_create(
                name=title,
                defaults={"description": description, "schema": schema},
            )

            schemas[title] = schema_object
            return schema_object

        for obj in Model.objects.all():
            schema = getattr(obj, field, None)

            if schema is None:
                continue

            schema_object = get_schema_object_from_schema(schema)
            setattr(obj, f"{field}_tmp", schema_object)
            obj.save()

    return python_migration


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_schemas", "0002_auto_20201018_2158"),
        ("irekua_types", "0002_auto_20201013_0048"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtype",
            name="annotation_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="annotation_schema_id",
                help_text="JSON Schema for annotation info",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotation_schema",
                to="irekua_schemas.schema",
                verbose_name="annotation schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key(
                "AnnotationType", "annotation_schema"
            )
        ),
        migrations.RemoveField(
            model_name="annotationtype",
            name="annotation_schema",
        ),
        migrations.RenameField(
            model_name="annotationtype",
            old_name="annotation_schema_tmp",
            new_name="annotation_schema",
        ),
        migrations.AddField(
            model_name="annotationtype",
            name="metadata_schema",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annotationtype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.AddField(
            model_name="deploymenttype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deploymenttype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key(
                "DeploymentType", "metadata_schema"
            )
        ),
        migrations.RemoveField(
            model_name="deploymenttype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="deploymenttype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
        migrations.AddField(
            model_name="eventtype",
            name="metadata_schema",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventtype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="metadata_schema",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itemtype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.AddField(
            model_name="licencetype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licencetype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key("LicenceType", "metadata_schema")
        ),
        migrations.RemoveField(
            model_name="licencetype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="licencetype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
        migrations.AddField(
            model_name="localitytype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localitytype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key("LocalityType", "metadata_schema")
        ),
        migrations.RemoveField(
            model_name="localitytype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="localitytype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
        migrations.AddField(
            model_name="mimetype",
            name="media_info_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="media_info_schema_id",
                help_text="JSON Schema for item type media info",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_info_schema",
                to="irekua_schemas.schema",
                verbose_name="media info schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key("MimeType", "media_info_schema")
        ),
        migrations.RemoveField(
            model_name="mimetype",
            name="media_info_schema",
        ),
        migrations.RenameField(
            model_name="mimetype",
            old_name="media_info_schema_tmp",
            new_name="media_info_schema",
        ),
        migrations.AddField(
            model_name="samplingeventtype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samplingeventtype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key(
                "SamplingEventType", "metadata_schema"
            )
        ),
        migrations.RemoveField(
            model_name="samplingeventtype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="samplingeventtype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
        migrations.AddField(
            model_name="sitedescriptortype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sitedescriptortype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key(
                "SiteDescriptorType", "metadata_schema"
            )
        ),
        migrations.RemoveField(
            model_name="sitedescriptortype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="sitedescriptortype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
        migrations.AddField(
            model_name="sitetype",
            name="metadata_schema_tmp",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sitetype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
        migrations.RunPython(
            move_json_schema_to_foreign_key("SiteType", "metadata_schema")
        ),
        migrations.RemoveField(
            model_name="sitetype",
            name="metadata_schema",
        ),
        migrations.RenameField(
            model_name="sitetype",
            old_name="metadata_schema_tmp",
            new_name="metadata_schema",
        ),
    ]
