# Generated by Django 3.1.2 on 2020-10-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_items", "0005_update_device_type_models_reference"),
        ("irekua_organisms", "0002_update_device_type_models_reference"),
        ("irekua_devices", "0004_include_device_type_models"),
        ("irekua_collections", "0011_update_device_type_models_reference"),
        ("irekua_types", "0007_relocate_item_type_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="mimetype",
                    name="media_info_schema",
                ),
                migrations.DeleteModel(
                    name="DeviceType",
                ),
                migrations.DeleteModel(
                    name="MimeType",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="DeviceType",
                    table="irekua_devices_devicetype",
                ),
                migrations.AlterModelTable(
                    name="MimeType",
                    table="irekua_devices_mimetype",
                ),
            ],
        ),
    ]
