# Generated by Django 3.1.2 on 2020-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_collections", "0007_auto_20201020_1547"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectiondevice",
            old_name="metadata",
            new_name="collection_metadata",
        ),
        migrations.RenameField(
            model_name="collectionuser",
            old_name="metadata",
            new_name="collection_metadata",
        ),
        migrations.AlterField(
            model_name="collectiondevice",
            name="collection_metadata",
            field=models.JSONField(
                blank=True,
                db_column="collection_metadata",
                help_text="Metadata associated with device within collection",
                null=True,
                verbose_name="collection metadata",
            ),
        ),
        migrations.AlterField(
            model_name="collectionuser",
            name="collection_metadata",
            field=models.JSONField(
                blank=True,
                db_column="collection_metadata",
                help_text="Metadata associated to user in collection",
                null=True,
                verbose_name="collection metadata",
            ),
        ),
    ]
