# Generated by Django 3.1.2 on 2020-10-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_geo", "0003_include_site_type_models"),
        ("irekua_collections", "0011_update_device_type_models_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="collectionsite",
                    name="site_type",
                    field=models.ForeignKey(
                        db_column="site_type",
                        help_text="Type of site",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_geo.sitetype",
                        verbose_name="site type",
                    ),
                ),
                migrations.AlterField(
                    model_name="collectiontype",
                    name="site_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Types of sites valid for collections of type",
                        through="irekua_collections.CollectionTypeSiteType",
                        to="irekua_geo.SiteType",
                        verbose_name="site types",
                    ),
                ),
                migrations.AlterField(
                    model_name="collectiontypesitetype",
                    name="site_type",
                    field=models.ForeignKey(
                        db_column="site_type_id",
                        help_text="Site type to be admissible in collections of this type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_geo.sitetype",
                        verbose_name="site type",
                    ),
                ),
                migrations.AlterField(
                    model_name="samplingeventtype",
                    name="site_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Valid site types for this sampling event type",
                        to="irekua_geo.SiteType",
                        verbose_name="site types",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
