# Generated by Django 3.1.2 on 2020-10-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_annotations", "0001_initial"),
        ("irekua_collections", "0012_update_site_type_models_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="collectiontype",
                    name="annotation_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Types of annotations valid for collections of type",
                        through="irekua_collections.CollectionTypeAnnotationType",
                        to="irekua_annotations.AnnotationType",
                        verbose_name="annotation types",
                    ),
                ),
                migrations.AlterField(
                    model_name="collectiontype",
                    name="event_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Types of events valid for collections of type",
                        through="irekua_collections.CollectionTypeEventType",
                        to="irekua_annotations.EventType",
                        verbose_name="event types",
                    ),
                ),
                migrations.AlterField(
                    model_name="collectiontypeannotationtype",
                    name="annotation_type",
                    field=models.ForeignKey(
                        db_column="annotation_type_id",
                        help_text="Annotation type to be admissible in collections of this type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_annotations.annotationtype",
                        verbose_name="annotation type",
                    ),
                ),
                migrations.AlterField(
                    model_name="collectiontypeeventtype",
                    name="event_type",
                    field=models.ForeignKey(
                        db_column="event_type_id",
                        help_text="Event type to be admissible in collections of this type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_annotations.eventtype",
                        verbose_name="event type",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
