# Generated by Django 3.1.2 on 2020-10-27 21:52

from django.db import migrations, models
import django.db.models.deletion

from tqdm import tqdm


def add_references_to_site_and_device_items(apps, schema_editor):
    SiteItem = apps.get_model('irekua_collections', 'SiteItem')
    SamplingEventItem = apps.get_model('irekua_collections', 'SamplingEventItem')
    total = SamplingEventItem.objects.count()
    for sampling_event_item in tqdm(SamplingEventItem.objects.all(), total=total):
        collection_site = sampling_event_item.sampling_event.collection_site
        collection_item = sampling_event_item.collectionitem_ptr

        site_item = SiteItem(
            site_item=collection_item,
            collection_site=collection_site)
        site_item.__dict__.update(collection_item.__dict__)
        site_item.save()

        sampling_event_item.siteitem_ptr = site_item
        sampling_event_item.save()

    assert total == SiteItem.objects.count()

    DeviceItem = apps.get_model('irekua_collections', 'DeviceItem')
    DeploymentItem = apps.get_model('irekua_collections', 'DeploymentItem')
    total = DeploymentItem.objects.count()
    for deployment_item in tqdm(DeploymentItem.objects.all(), total=total):
        collection_device = deployment_item.deployment.collection_device
        collection_item = deployment_item.samplingeventitem_ptr.collectionitem_ptr

        device_item = DeviceItem(
            device_item=collection_item,
            collection_device=collection_device)
        device_item.__dict__.update(collection_item.__dict__)
        device_item.save()

        deployment_item.deviceitem_ptr = device_item
        deployment_item.save()

    assert total == DeviceItem.objects.count()


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_collections', '0014_collectionannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentitem',
            name='samplingeventitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='irekua_collections.samplingeventitem'),
        ),
        migrations.CreateModel(
            name='SiteItem',
            fields=[
                ('site_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='irekua_collections.collectionitem')),
                ('collection_site', models.ForeignKey(db_column='collection_site_id', help_text='Site in which this item was captured', on_delete=django.db.models.deletion.PROTECT, to='irekua_collections.collectionsite', verbose_name='collection site')),
            ],
            options={
                'verbose_name': 'Site Item',
                'verbose_name_plural': 'Site Items',
                'ordering': ['-created_on'],
            },
            bases=('irekua_collections.collectionitem',),
        ),
        migrations.CreateModel(
            name='DeviceItem',
            fields=[
                ('device_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='irekua_collections.collectionitem')),
                ('collection_device', models.ForeignKey(db_column='collection_device_id', help_text='Device used to capture the item', on_delete=django.db.models.deletion.PROTECT, to='irekua_collections.collectiondevice', verbose_name='collection device')),
            ],
            options={
                'verbose_name': 'Device Item',
                'verbose_name_plural': 'Device Items',
                'ordering': ['-created_on'],
            },
            bases=('irekua_collections.collectionitem',),
        ),
        migrations.AddField(
            model_name='deploymentitem',
            name='deviceitem_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='irekua_collections.deviceitem'),
        ),
        migrations.AddField(
            model_name='samplingeventitem',
            name='siteitem_ptr',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, serialize=False, to='irekua_collections.siteitem'),
        ),
        migrations.RunPython(
            add_references_to_site_and_device_items,
        ),
    ]
