# Generated by Django 3.1.2 on 2020-11-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_collections", "0017_add_site_and_device_level_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingeventtype",
            name="deployment_distance",
            field=models.FloatField(
                blank=True,
                db_column="deployment_distance",
                default=0,
                help_text="Maximum distance to site at which a device can be deployed",
                verbose_name="deployment distance",
            ),
        ),
        migrations.AddField(
            model_name="samplingeventtype",
            name="restrict_deployment_positions",
            field=models.BooleanField(
                db_column="restrict_deployment_positions",
                default=False,
                help_text="Determines whether deployment positions are checked. When true all deployments must occurr within some distance to the site.",
                verbose_name="restrict deployment positions",
            ),
        ),
    ]
