# Generated by Django 3.1.2 on 2020-11-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_collections", "0018_add_deployment_config_to_sampling_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionsite",
            name="parent_site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Site to which this site belongs if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="irekua_collections.collectionsite",
                verbose_name="parent site",
            ),
        ),
    ]
