# Generated by Django 3.1.2 on 2020-12-03 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_collections", "0019_add_parent_site_to_collection_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplingevent",
            name="parent_sampling_event",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_sampling_event",
                help_text="Is this sampling event is part of a larger sampling event?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="irekua_collections.samplingevent",
                verbose_name="parent sampling event",
            ),
        ),
        migrations.AddField(
            model_name="samplingeventtype",
            name="can_have_subsampling_events",
            field=models.BooleanField(
                blank=True,
                db_column="can_have_subsampling_events",
                default=False,
                help_text="Determines if sampling events of this type can have sub-sampling events",
                verbose_name="can have subsampling events",
            ),
        ),
        migrations.AddField(
            model_name="samplingeventtype",
            name="restrict_subsampling_event_types",
            field=models.BooleanField(
                blank=True,
                db_column="restrict_subsampling_event_types",
                default=True,
                help_text="If false a sampling event of any type can be declared as a subsampling event for sampling events of this type.",
                verbose_name="restrict subsampling event types",
            ),
        ),
        migrations.AddField(
            model_name="samplingeventtype",
            name="subsampling_event_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of sampling event types that can be registered as subsampling events of sampling events of this type.",
                related_name="_samplingeventtype_subsampling_event_types_+",
                to="irekua_collections.SamplingEventType",
                verbose_name="subsampling event types",
            ),
        ),
    ]
