# Generated by Django 3.1.2 on 2020-12-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_collections", "0020_add_parent_sampling_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingevent",
            name="collection_site",
            field=models.ForeignKey(
                db_column="collection_site_id",
                help_text="Reference to site at which sampling took place",
                on_delete=django.db.models.deletion.PROTECT,
                to="irekua_collections.collectionsite",
                verbose_name="collection site",
            ),
        ),
    ]
