# Generated by Django 3.1.2 on 2020-12-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_annotations", "0004_auto_20201024_2241"),
        ("irekua_thumbnails", "0002_auto_20201026_1109"),
        ("irekua_collections", "0022_create_new_single_item_model"),
        ("irekua_items", "0013_mediainfoextractor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionitem",
            name="item_ptr",
        ),
        migrations.RemoveField(
            model_name="deploymentitem",
            name="deployment",
        ),
        migrations.RemoveField(
            model_name="deploymentitem",
            name="deviceitem_ptr",
        ),
        migrations.RemoveField(
            model_name="deploymentitem",
            name="samplingeventitem_ptr",
        ),
        migrations.RemoveField(
            model_name="deviceitem",
            name="collection_device",
        ),
        migrations.RemoveField(
            model_name="deviceitem",
            name="device_item",
        ),
        migrations.RemoveField(
            model_name="samplingeventitem",
            name="sampling_event",
        ),
        migrations.RemoveField(
            model_name="samplingeventitem",
            name="siteitem_ptr",
        ),
        migrations.RemoveField(
            model_name="siteitem",
            name="collection_site",
        ),
        migrations.RemoveField(
            model_name="siteitem",
            name="site_item",
        ),
        migrations.DeleteModel(
            name="CollectionItem",
        ),
        migrations.DeleteModel(
            name="DeploymentItem",
        ),
        migrations.DeleteModel(
            name="DeviceItem",
        ),
        migrations.DeleteModel(
            name="SamplingEventItem",
        ),
        migrations.DeleteModel(
            name="SiteItem",
        ),
    ]
