# Generated by Django 3.1.2 on 2020-12-16 01:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_thumbnails", "0002_auto_20201026_1109"),
        ("irekua_models", "0009_modelrun"),
        ("irekua_items", "0013_mediainfoextractor"),
        ("irekua_annotations", "0004_auto_20201024_2241"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irekua_collections", "0023_remove_old_item_models"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollectionItemTmp",
            new_name="CollectionItem",
        ),
    ]
