# Generated by Django 3.1.2 on 2020-12-17 23:34

from django.db import migrations, models


def move_institutions(apps, schema_editor):
    Collection = apps.get_model("irekua_collections", "Collection")

    for collection in Collection.objects.all():
        if collection.institution is not None:
            collection.institutions.add(collection.institution)
            collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_database", "0014_auto_20201017_2008"),
        ("irekua_collections", "0024_rename_new_item_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="institutions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Institutions to which the collection belogs",
                to="irekua_database.Institution",
                verbose_name="institutions",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="metadata",
            field=models.JSONField(
                blank=True,
                db_column="metadata",
                help_text="Metadata associated to collection",
                null=True,
                verbose_name="metadata",
            ),
        ),
        migrations.RunPython(
            move_institutions,
        ),
        migrations.RemoveField(
            model_name="collection",
            name="institution",
        ),
    ]
