# Generated by Django 3.1 on 2021-06-17 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irekua_collections', '0026_auto_20201218_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsite',
            name='associated_users',
            field=models.ManyToManyField(blank=True, help_text='List of collection users that are associated to this site.', to=settings.AUTH_USER_MODEL, verbose_name='associated users'),
        ),
    ]
