# Generated by Django 3.1.2 on 2020-10-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0003_change_item_type_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizer',
            name='configuration_schema',
            field=models.JSONField(blank=True, db_column='configuration_schema', help_text='JSON schema for annotation tool configuration info', null=True, verbose_name='configuration schema'),
        ),
    ]
