# Generated by Django 3.1.2 on 2020-10-25 16:33
import json
from django.db import migrations, models
import django.db.models.deletion


def add_schema_reference(apps, schema_editor):
    Schema = apps.get_model('irekua_schemas', 'Schema')
    VisualizerVersion = apps.get_model('selia_visualizers', 'VisualizerVersion')

    schemas = {}
    def get_schema_object_from_schema(schema):
        if isinstance(schema, str):
            schema = json.loads(schema)

        title = schema.get('title', None)
        description = schema.get('description', '')

        if title is None:
            return None

        if title in schemas:
            return schemas[title]

        schema_object, _ = Schema.objects.get_or_create(
            name=title,
            defaults={
                'description': description,
                'schema': schema
            }
        )

        schemas[title] = schema_object
        return schema_object

    for obj in VisualizerVersion.objects.all():
        schema = obj.configuration_schema

        if schema is None:
            continue

        schema_object = get_schema_object_from_schema(schema)
        obj.configuration_schema_tmp = schema_object
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_schemas', '0002_auto_20201018_2158'),
        ('selia_visualizers', '0007_auto_20201024_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizer',
            name='version',
        ),
        migrations.AlterField(
            model_name='annotationvisualizer',
            name='visualizer_configuration',
            field=models.JSONField(blank=True, db_column='visualizer_configuration', help_text='Configuration of visualizer at annotation creation', null=True, verbose_name='visualizer configuration'),
        ),
        migrations.AddField(
            model_name='visualizerversion',
            name='configuration_schema_tmp',
            field=models.ForeignKey(blank=True, db_column='configuration_schema_id', help_text='JSON schema for visualizer tool configuration info', null=True, on_delete=django.db.models.deletion.PROTECT, to='irekua_schemas.schema', verbose_name='configuration schema'),
        ),
        migrations.RunPython(
            add_schema_reference,
        ),
        migrations.RemoveField(
            model_name='visualizerversion',
            name='configuration_schema',
        ),
        migrations.RenameField(
            model_name='visualizerversion',
            old_name='configuration_schema_tmp',
            new_name='configuration_schema',
        ),
    ]
