# Generated by Django 3.1.2 on 2020-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0008_update_schema_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizer',
            name='name',
            field=models.CharField(db_column='name', help_text='Name of visualizer app', max_length=64, unique=True, verbose_name='name'),
        ),
    ]
