# Generated by Django 3.1 on 2020-10-13 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irekua_database.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("irekua_types", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="DeviceBrand",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_on",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_column="created_on",
                                help_text="Date of creation",
                                verbose_name="created on",
                            ),
                        ),
                        (
                            "modified_on",
                            models.DateTimeField(
                                auto_now=True,
                                db_column="modified_on",
                                help_text="Date of last modification",
                                verbose_name="modified on",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                db_column="name",
                                help_text="Name of device brand",
                                max_length=128,
                                unique=True,
                                verbose_name="name",
                            ),
                        ),
                        (
                            "website",
                            models.URLField(
                                blank=True,
                                db_column="website",
                                help_text="Brand's website",
                                null=True,
                                verbose_name="website",
                            ),
                        ),
                        (
                            "logo",
                            models.ImageField(
                                blank=True,
                                db_column="logo",
                                help_text="Logo of device brand",
                                null=True,
                                upload_to="images/device_brands/",
                                verbose_name="logo",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Device Brand",
                        "verbose_name_plural": "Device Brands",
                        "ordering": ["name"],
                    },
                ),
                migrations.CreateModel(
                    name="Device",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_on",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_column="created_on",
                                help_text="Date of creation",
                                verbose_name="created on",
                            ),
                        ),
                        (
                            "modified_on",
                            models.DateTimeField(
                                auto_now=True,
                                db_column="modified_on",
                                help_text="Date of last modification",
                                verbose_name="modified on",
                            ),
                        ),
                        (
                            "model",
                            models.CharField(
                                db_column="model",
                                help_text="Model of device",
                                max_length=64,
                                verbose_name="model",
                            ),
                        ),
                        (
                            "metadata_schema",
                            models.JSONField(
                                blank=True,
                                db_column="metadata_schema",
                                default=irekua_database.utils.simple_JSON_schema,
                                help_text="JSON Schema for metadata of device info",
                                validators=[
                                    irekua_database.utils.validate_JSON_schema
                                ],
                                verbose_name="metadata schema",
                            ),
                        ),
                        (
                            "configuration_schema",
                            models.JSONField(
                                blank=True,
                                db_column="configuration_schema",
                                default=irekua_database.utils.simple_JSON_schema,
                                help_text="JSON Schema for configuration info of device",
                                validators=[
                                    irekua_database.utils.validate_JSON_schema
                                ],
                                verbose_name="configuration schema",
                            ),
                        ),
                        (
                            "brand",
                            models.ForeignKey(
                                db_column="device_brand_id",
                                help_text="Brand of device",
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="device_brand",
                                to="irekua_devices.devicebrand",
                                verbose_name="brand",
                            ),
                        ),
                        (
                            "device_type",
                            models.ForeignKey(
                                db_column="device_type_id",
                                help_text="Type of device",
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="device_type",
                                to="irekua_types.devicetype",
                                verbose_name="device type",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Device",
                        "verbose_name_plural": "Devices",
                        "ordering": ["brand", "model"],
                        "unique_together": {("brand", "model")},
                    },
                ),
                migrations.CreateModel(
                    name="PhysicalDevice",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_on",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_column="created_on",
                                help_text="Date of creation",
                                verbose_name="created on",
                            ),
                        ),
                        (
                            "modified_on",
                            models.DateTimeField(
                                auto_now=True,
                                db_column="modified_on",
                                help_text="Date of last modification",
                                verbose_name="modified on",
                            ),
                        ),
                        (
                            "identifier",
                            models.CharField(
                                blank=True,
                                db_column="identifier",
                                help_text="Simple device identifier (visible only to owner)",
                                max_length=128,
                                verbose_name="name",
                            ),
                        ),
                        (
                            "serial_number",
                            models.CharField(
                                blank=True,
                                db_column="serial_number",
                                help_text="Serial number of device",
                                max_length=128,
                                null=True,
                                verbose_name="serial number",
                            ),
                        ),
                        (
                            "metadata",
                            models.JSONField(
                                blank=True,
                                db_column="metadata",
                                default=irekua_database.utils.empty_JSON,
                                help_text="Metadata associated to device",
                                null=True,
                                verbose_name="metadata",
                            ),
                        ),
                        (
                            "bundle",
                            models.BooleanField(
                                db_column="bundle",
                                help_text="Does this device possibly represents many physical devices?",
                                verbose_name="bundle",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                db_column="creator_id",
                                help_text="Creator of object",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="physicaldevice_created_by",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="creator",
                            ),
                        ),
                        (
                            "device",
                            models.ForeignKey(
                                db_column="device_id",
                                help_text="Brand and model of device",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="irekua_devices.device",
                                verbose_name="device",
                            ),
                        ),
                        (
                            "modified_by",
                            models.ForeignKey(
                                blank=True,
                                db_column="modified_by",
                                editable=False,
                                help_text="User who made modifications last",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="physicaldevice_modified_by",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="modified by",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Physical Device",
                        "verbose_name_plural": "Physical Devices",
                        "ordering": ["-created_on"],
                        "unique_together": {("serial_number", "device")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
