# Generated by Django 3.1.2 on 2020-10-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_devices", "0005_auto_20201021_2034"),
        ("irekua_items", "0009_add_mime_type"),
        ("irekua_types", "0008_relocate_device_type_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="mimetype",
                    name="media_info_schema",
                ),
                migrations.AlterField(
                    model_name="devicetype",
                    name="mime_types",
                    field=models.ManyToManyField(
                        blank=True,
                        db_column="mime_types",
                        help_text="Possible mime types for files generated by devicesof this type",
                        to="irekua_items.MimeType",
                        verbose_name="mime types",
                    ),
                ),
                migrations.DeleteModel(
                    name="MimeType",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="MimeType",
                    table="irekua_items_mimetype",
                ),
            ],
        ),
    ]
