# Generated by Django 3.1.2 on 2020-11-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_devices", "0006_move_mime_type_to_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="physicaldevice",
            old_name="metadata",
            new_name="device_metadata",
        ),
        migrations.AddField(
            model_name="physicaldevice",
            name="device_type_metadata",
            field=models.JSONField(
                blank=True,
                db_column="device_type_metadata",
                help_text="Metadata associated to the device type",
                null=True,
                verbose_name="device type metadata",
            ),
        ),
        migrations.AlterField(
            model_name="physicaldevice",
            name="device_metadata",
            field=models.JSONField(
                blank=True,
                db_column="device_metadata",
                help_text="Metadata associated to device",
                null=True,
                verbose_name="device metadata",
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="metadata_schema",
            field=models.ForeignKey(
                blank=True,
                db_column="metadata_schema_id",
                help_text="JSON Schema for additional metadata",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devicetype_metadata_schema",
                to="irekua_schemas.schema",
                verbose_name="metadata schema",
            ),
        ),
    ]
