# Generated by Django 3.1.2 on 2020-12-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_schemas", "0002_auto_20201018_2158"),
        ("irekua_devices", "0007_add_device_type_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="configuration_schema",
            field=models.ForeignKey(
                blank=True,
                db_column="configuration_schema_id",
                help_text="JSON Schema for configuration info of device",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configuration_schema",
                to="irekua_schemas.schema",
                verbose_name="configuration schema",
            ),
        ),
    ]
