# Generated by Django 3.1 on 2021-03-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_items", "0015_remove_mediainfoextractor"),
        ("irekua_devices", "0008_auto_20201217_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="mime_types",
            field=models.ManyToManyField(
                blank=True,
                db_column="mime_types",
                help_text="Possible mime types for files generated by devices of this type",
                to="irekua_items.MimeType",
                verbose_name="mime types",
            ),
        ),
    ]
