# Generated by Django 3.1.2 on 2020-10-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_organisms', '0003_update_schema_to_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='additional_metadata',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='organismcapture',
            old_name='additional_metadata',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='organism',
            name='collection_metadata',
            field=models.JSONField(blank=True, db_column='collection_metadata', help_text='Additional metadata associated to organism in collection', null=True, verbose_name='collection metadata'),
        ),
        migrations.AddField(
            model_name='organismcapture',
            name='collection_metadata',
            field=models.JSONField(blank=True, db_column='collection_metadata', help_text='Additional metadata associated to organism capture in collection', null=True, verbose_name='collection metadata'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='metadata',
            field=models.JSONField(blank=True, db_column='metadata', help_text='Additional metadata associated to organism', null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='organismcapture',
            name='metadata',
            field=models.JSONField(blank=True, db_column='metadata', help_text='Additional metadata associated to organism capture', null=True, verbose_name='metadata'),
        ),
    ]
