# Generated by Django 3.1.2 on 2020-10-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_organisms', '0004_added_collection_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontypeorganismconfig',
            name='restrict_organism_capture_types',
            field=models.BooleanField(blank=True, db_column='restrict_organism_capture_types', default=True, help_text='Flag indicating whether types of organism captures are restricted to registered ones', verbose_name='restrict organism capture types'),
        ),
        migrations.AddField(
            model_name='collectiontypeorganismconfig',
            name='restrict_organism_types',
            field=models.BooleanField(blank=True, db_column='restrict_organism_types', default=True, help_text='Flag indicating whether types of organisms are restricted to registered ones', verbose_name='restrict organism types'),
        ),
    ]
