# Generated by Django 3.1.2 on 2020-10-22 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_organisms', '0005_added_restriction_option_to_organism_config'),
        ('irekua_types', '0007_relocate_item_type_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismcapture',
            old_name='sampling_event_device',
            new_name='deployment',
        ),
        migrations.AlterField(
            model_name='organism',
            name='identification_info',
            field=models.JSONField(blank=True, db_column='identification_info', help_text='Organism identification information.', verbose_name='identification info'),
        ),
        migrations.AddField(
            model_name='organismcapturetype',
            name='item_types',
            field=models.ManyToManyField(blank=True, help_text='Types of items that can be associated to organism captures of this type.', to='irekua_items.ItemType', verbose_name='item types'),
        ),
        migrations.AddField(
            model_name='organismcapturetype',
            name='restrict_item_types',
            field=models.BooleanField(blank=True, db_column='restrict_item_types', default=True, help_text='Flag indicating whether any type of item can be associated to captures of this type', verbose_name='restrict item types'),
        ),
        migrations.AddField(
            model_name='organismtype',
            name='item_types',
            field=models.ManyToManyField(blank=True, help_text='Types of items that can be associated to organism of this type.', to='irekua_items.ItemType', verbose_name='item types'),
        ),
        migrations.AddField(
            model_name='organismtype',
            name='restrict_item_types',
            field=models.BooleanField(blank=True, db_column='restrict_item_types', default=True, help_text='Flag indicating whether any type of item can be associated to organisms of this type', verbose_name='restrict item types'),
        ),
        migrations.AlterField(
            model_name='organismcapture',
            name='deployment',
            field=models.ForeignKey(db_column='deployment_id', help_text='Deployed device that capture this organism', on_delete=django.db.models.deletion.PROTECT, to='irekua_collections.deployment', verbose_name='deployment'),
        ),
    ]
