# Generated by Django 3.1.2 on 2020-12-10 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irekua_organisms.models.organism_items


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_terms", "0007_auto_20201202_2110"),
        ("irekua_schemas", "0002_auto_20201018_2158"),
        ("irekua_collections", "0021_auto_20201203_1407"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("irekua_items", "0013_mediainfoextractor"),
        ("irekua_organisms", "0007_auto_20201022_0125"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganismItem",
            fields=[
                (
                    "collectionitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_collections.collectionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Item",
                "verbose_name_plural": "Organism Items",
                "ordering": ["-created_on"],
            },
            bases=(
                "irekua_collections.collectionitem",
                irekua_organisms.models.organism_items.OrganismItemMixin,
            ),
        ),
        migrations.CreateModel(
            name="OrganismObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_on",
                        help_text="Date of creation",
                        verbose_name="created on",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified_on",
                        help_text="Date of last modification",
                        verbose_name="modified on",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_column="metadata",
                        help_text="Additional metadata associated to organism observation",
                        null=True,
                        verbose_name="metadata",
                    ),
                ),
                (
                    "collection_metadata",
                    models.JSONField(
                        blank=True,
                        db_column="collection_metadata",
                        help_text="Additional metadata associated to organism observation in collection",
                        null=True,
                        verbose_name="collection metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="creator_id",
                        help_text="Creator of object",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismobservation_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creator",
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Description of the organism observation",
                        to="irekua_terms.Term",
                        verbose_name="labels",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="modified_by",
                        editable=False,
                        help_text="User who made modifications last",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organismobservation_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        db_column="organism_id",
                        help_text="Observed organism",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_organisms.organism",
                        verbose_name="organism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Observation",
                "verbose_name_plural": "Organism Observations",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddField(
            model_name="collectiontypeorganismconfig",
            name="restrict_organism_observation_types",
            field=models.BooleanField(
                blank=True,
                db_column="restrict_organism_observation_types",
                default=True,
                help_text="Flag indicating whether types of organism observation are restricted to registered ones",
                verbose_name="restrict organism observation types",
            ),
        ),
        migrations.CreateModel(
            name="OrganismObservationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_on",
                        help_text="Date of creation",
                        verbose_name="created on",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified_on",
                        help_text="Date of last modification",
                        verbose_name="modified on",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name",
                        help_text="Name of organism observation type",
                        max_length=64,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_column="description",
                        help_text="Description of organism capture type",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        db_column="icon",
                        help_text="Organism observation type icon",
                        null=True,
                        upload_to="images/organism_observation_types/",
                        verbose_name="icon",
                    ),
                ),
                (
                    "restrict_item_types",
                    models.BooleanField(
                        blank=True,
                        db_column="restrict_item_types",
                        default=True,
                        help_text="Flag indicating whether any type of item can be associated to observations of this type",
                        verbose_name="restrict item types",
                    ),
                ),
                (
                    "item_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Types of items that can be associated to organism observations of this type.",
                        to="irekua_items.ItemType",
                        verbose_name="item types",
                    ),
                ),
                (
                    "metadata_schema",
                    models.ForeignKey(
                        blank=True,
                        db_column="metadata_schema_id",
                        help_text="JSON Schema for additional metadata",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organismobservationtype_metadata_schema",
                        to="irekua_schemas.schema",
                        verbose_name="metadata schema",
                    ),
                ),
                (
                    "organism_type",
                    models.ForeignKey(
                        db_column="organism_type_id",
                        help_text="Organism type being observed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irekua_organisms.organismtype",
                        verbose_name="organism type",
                    ),
                ),
                (
                    "sampling_event_types",
                    models.ManyToManyField(
                        help_text="Sampling event types on which this types of observation are made",
                        to="irekua_collections.SamplingEventType",
                        verbose_name="sampling event types",
                    ),
                ),
                (
                    "term_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Valid term types to describe the organism observation",
                        to="irekua_terms.TermType",
                        verbose_name="term types",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Observation Type",
                "verbose_name_plural": "Organism Observation Types",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="OrganismObservationItem",
            fields=[
                (
                    "samplingeventitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_collections.samplingeventitem",
                    ),
                ),
                (
                    "organism_observation",
                    models.ForeignKey(
                        db_column="organism_observation_id",
                        help_text="Organism observation to which item belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_organisms.organismobservation",
                        verbose_name="organism observation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Observation Item",
                "verbose_name_plural": "Organism Observation Items",
                "ordering": ["-created_on"],
            },
            bases=(
                "irekua_collections.samplingeventitem",
                irekua_organisms.models.organism_items.OrganismItemMixin,
            ),
        ),
        migrations.AddField(
            model_name="organismobservation",
            name="organism_observation_type",
            field=models.ForeignKey(
                db_column="organism_observation_type_id",
                help_text="Observation type",
                on_delete=django.db.models.deletion.PROTECT,
                to="irekua_organisms.organismobservationtype",
                verbose_name="organism observation type",
            ),
        ),
        migrations.AddField(
            model_name="organismobservation",
            name="sampling_event",
            field=models.ForeignKey(
                db_column="sampling_event_id",
                help_text="Sampling event in which the organism was observed",
                on_delete=django.db.models.deletion.PROTECT,
                to="irekua_collections.samplingevent",
                verbose_name="sampling_event",
            ),
        ),
        migrations.CreateModel(
            name="OrganismCaptureItem",
            fields=[
                (
                    "deploymentitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="irekua_collections.deploymentitem",
                    ),
                ),
                (
                    "capture",
                    models.ForeignKey(
                        db_column="organism_capture_id",
                        help_text="Organism to which item belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_organisms.organismcapture",
                        verbose_name="organism",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Capture Item",
                "verbose_name_plural": "Organism Capture Items",
                "ordering": ["-created_on"],
            },
            bases=(
                "irekua_collections.deploymentitem",
                irekua_organisms.models.organism_items.OrganismItemMixin,
            ),
        ),
        migrations.CreateModel(
            name="CollectionTypeOrganismObservationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_on",
                        help_text="Date of creation",
                        verbose_name="created on",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified_on",
                        help_text="Date of last modification",
                        verbose_name="modified on",
                    ),
                ),
                (
                    "collection_type_organism_config",
                    models.ForeignKey(
                        db_column="collection_type_organism_config_id",
                        help_text="Collection type organism configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irekua_organisms.collectiontypeorganismconfig",
                        verbose_name="collection type organism config",
                    ),
                ),
                (
                    "metadata_schema",
                    models.ForeignKey(
                        blank=True,
                        db_column="metadata_schema_id",
                        help_text="JSON Schema for collection-specific metadata",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collectiontypeorganismobservationtype_metadata_schema",
                        to="irekua_schemas.schema",
                        verbose_name="metadata schema",
                    ),
                ),
                (
                    "organism_observation_type",
                    models.ForeignKey(
                        db_column="organism_observation_type_id",
                        help_text="Organism observation type to be registered to the collection type",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_organisms.organismobservationtype",
                        verbose_name="organism observation type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Type Organism Observation Type",
                "verbose_name_plural": "Collection Type Organism Observation Types",
                "ordering": ["-created_on"],
                "unique_together": {
                    ("collection_type_organism_config", "organism_observation_type")
                },
            },
        ),
        migrations.AddField(
            model_name="collectiontypeorganismconfig",
            name="organism_observation_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Types of organism observation that can be registered into collections of this type.",
                through="irekua_organisms.CollectionTypeOrganismObservationType",
                to="irekua_organisms.OrganismObservationType",
                verbose_name="organism observation types",
            ),
        ),
    ]
