# Generated by Django 3.1.2 on 2020-10-24 23:26

from django.db import migrations, models
import irekua_database.utils


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_models', '0004_update_types_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprediction',
            name='annotation',
            field=models.JSONField(db_column='annotation', default=irekua_database.utils.empty_JSON, help_text='Information of annotation location within item', verbose_name='annotation'),
        ),
    ]
