# Generated by Django 3.1.2 on 2020-12-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("irekua_items", "0013_mediainfoextractor"),
        ("irekua_models", "0008_remove_old_model_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_on",
                        help_text="Date of creation",
                        verbose_name="created on",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="modified_on",
                        help_text="Date of last modification",
                        verbose_name="modified on",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        help_text="Item on which the model was run",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="irekua_items.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        db_column="model_version_id",
                        help_text="Model and version used for item processing",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="irekua_models.modelversion",
                        verbose_name="model version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Run",
                "verbose_name_plural": "Model Runs",
                "ordering": ["-modified_on"],
            },
        ),
    ]
