# Generated by Django 3.1.2 on 2020-12-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irekua_models', '0009_modelrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprediction',
            name='model_run',
            field=models.ForeignKey(blank=True, db_column='model_run_id', help_text='Model run in which this prediction was made', null=True, on_delete=django.db.models.deletion.PROTECT, to='irekua_models.modelrun', verbose_name='model run'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='creator_id', help_text='Creator of object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelrun_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', editable=False, help_text='User who made modifications last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelrun_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
