# Generated by Django 3.1.2 on 2020-10-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_annotations', '0003_annotation_userannotation'),
        ('irekua_visualizers', '0005_added_updated_visualizer_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualizermodule',
            options={'ordering': ['-created_on'], 'verbose_name': 'Visualizer Module', 'verbose_name_plural': 'Visualizer Modules'},
        ),
        migrations.CreateModel(
            name='AnnotationVisualizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('visualizer_configuration', models.JSONField(blank=True, db_column='visualizer_configuration', help_text='Configuration of visualizer at annotation creation', verbose_name='visualizer configuration')),
                ('annotation', models.OneToOneField(db_column='annotation_id', help_text='Annotation that was created using this visualizer', on_delete=django.db.models.deletion.CASCADE, to='irekua_annotations.annotation', verbose_name='annotation')),
                ('visualizer_version', models.ForeignKey(db_column='visualizer_version_id', help_text='Visualizer version used to create this annotation', on_delete=django.db.models.deletion.CASCADE, to='irekua_visualizers.visualizerversion', verbose_name='visualizer version')),
            ],
            options={
                'verbose_name': 'Annotation Visualizer',
                'verbose_name_plural': 'Annotation Visualizers',
                'ordering': ['-created_on'],
            },
        ),
    ]
