# Generated by Django 3.1.2 on 2020-10-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_visualizers', '0006_created_annotation_visualizer_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visualizercomponentitemtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visualizercomponentitemtype',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='visualizercomponentitemtype',
            name='visualizer_component',
        ),
        migrations.DeleteModel(
            name='VisualizerComponent',
        ),
        migrations.DeleteModel(
            name='VisualizerComponentItemType',
        ),
    ]
