name: Tests
on:
  pull_request:
    branches:
      - develop
      - irekua_cleanup
      - master
  push:
    branches:
      - develop
      - irekua_cleanup
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository
      uses: actions/checkout@v2
    - name: Start containers
      run: make up
    - name: Wait for database to start
      run: sleep 10
    - name: Run tests
      run: make test
