name: Tests
on:
  pull_request:
    branches:
      - irekua_cleanup
      - master
  push:
    branches:
      - irekua_cleanup
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: sudo docker-compose build
    - name: Verifica el formato
      run: docker-compose run app python manage.py test --keepdb
